name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    
    - name: Build
      run: dotnet build ./APIContagem --configuration Release

    - name: Publish
      run: dotnet publish ./APIContagem -c Release  --self-contained -r win-x64 -o app
    
    - name: Create Zip File
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./publicacao.zip ./app
    
    - uses: actions/upload-artifact@v1
      with:
        name: publicacao.zip
        path: ./app
        
    - name: Upload release
      uses: yakuhzi/action-release@v1
      with:
        file: ./app
        changelog: ./README.md
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
