name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    
    - name: Build com o utilitario dotnet
      run: dotnet build ./APIContagem --configuration Release

    - name: Publish com o utilitario dotnet
      run: dotnet publish ./APIContagem -c Release -o app
