name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    
    - name: Build
      run: dotnet build ./APIContagem --configuration Release

    - name: Publish
      run: dotnet publish ./APIContagem -c Release  --self-contained -r win-x64 -o app
